require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ObservacoesrelatoriosController do

  # This should return the minimal set of attributes required to create a valid
  # Observacoesrelatorio. As you add validations to Observacoesrelatorio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sivic_relatorioscelulas" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ObservacoesrelatoriosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all observacoesrelatorios as @observacoesrelatorios" do
      observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:observacoesrelatorios).should eq([observacoesrelatorio])
    end
  end

  describe "GET show" do
    it "assigns the requested observacoesrelatorio as @observacoesrelatorio" do
      observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
      get :show, {:id => observacoesrelatorio.to_param}, valid_session
      assigns(:observacoesrelatorio).should eq(observacoesrelatorio)
    end
  end

  describe "GET new" do
    it "assigns a new observacoesrelatorio as @observacoesrelatorio" do
      get :new, {}, valid_session
      assigns(:observacoesrelatorio).should be_a_new(Observacoesrelatorio)
    end
  end

  describe "GET edit" do
    it "assigns the requested observacoesrelatorio as @observacoesrelatorio" do
      observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
      get :edit, {:id => observacoesrelatorio.to_param}, valid_session
      assigns(:observacoesrelatorio).should eq(observacoesrelatorio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Observacoesrelatorio" do
        expect {
          post :create, {:observacoesrelatorio => valid_attributes}, valid_session
        }.to change(Observacoesrelatorio, :count).by(1)
      end

      it "assigns a newly created observacoesrelatorio as @observacoesrelatorio" do
        post :create, {:observacoesrelatorio => valid_attributes}, valid_session
        assigns(:observacoesrelatorio).should be_a(Observacoesrelatorio)
        assigns(:observacoesrelatorio).should be_persisted
      end

      it "redirects to the created observacoesrelatorio" do
        post :create, {:observacoesrelatorio => valid_attributes}, valid_session
        response.should redirect_to(Observacoesrelatorio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved observacoesrelatorio as @observacoesrelatorio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Observacoesrelatorio.any_instance.stub(:save).and_return(false)
        post :create, {:observacoesrelatorio => { "sivic_relatorioscelulas" => "invalid value" }}, valid_session
        assigns(:observacoesrelatorio).should be_a_new(Observacoesrelatorio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Observacoesrelatorio.any_instance.stub(:save).and_return(false)
        post :create, {:observacoesrelatorio => { "sivic_relatorioscelulas" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested observacoesrelatorio" do
        observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
        # Assuming there are no other observacoesrelatorios in the database, this
        # specifies that the Observacoesrelatorio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Observacoesrelatorio.any_instance.should_receive(:update).with({ "sivic_relatorioscelulas" => "" })
        put :update, {:id => observacoesrelatorio.to_param, :observacoesrelatorio => { "sivic_relatorioscelulas" => "" }}, valid_session
      end

      it "assigns the requested observacoesrelatorio as @observacoesrelatorio" do
        observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
        put :update, {:id => observacoesrelatorio.to_param, :observacoesrelatorio => valid_attributes}, valid_session
        assigns(:observacoesrelatorio).should eq(observacoesrelatorio)
      end

      it "redirects to the observacoesrelatorio" do
        observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
        put :update, {:id => observacoesrelatorio.to_param, :observacoesrelatorio => valid_attributes}, valid_session
        response.should redirect_to(observacoesrelatorio)
      end
    end

    describe "with invalid params" do
      it "assigns the observacoesrelatorio as @observacoesrelatorio" do
        observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Observacoesrelatorio.any_instance.stub(:save).and_return(false)
        put :update, {:id => observacoesrelatorio.to_param, :observacoesrelatorio => { "sivic_relatorioscelulas" => "invalid value" }}, valid_session
        assigns(:observacoesrelatorio).should eq(observacoesrelatorio)
      end

      it "re-renders the 'edit' template" do
        observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Observacoesrelatorio.any_instance.stub(:save).and_return(false)
        put :update, {:id => observacoesrelatorio.to_param, :observacoesrelatorio => { "sivic_relatorioscelulas" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested observacoesrelatorio" do
      observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
      expect {
        delete :destroy, {:id => observacoesrelatorio.to_param}, valid_session
      }.to change(Observacoesrelatorio, :count).by(-1)
    end

    it "redirects to the observacoesrelatorios list" do
      observacoesrelatorio = Observacoesrelatorio.create! valid_attributes
      delete :destroy, {:id => observacoesrelatorio.to_param}, valid_session
      response.should redirect_to(observacoesrelatorios_url)
    end
  end

end
