require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SivicContatosController do

  # This should return the minimal set of attributes required to create a valid
  # SivicContato. As you add validations to SivicContato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "desc_nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SivicContatosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sivic_contatos as @sivic_contatos" do
      sivic_contato = SivicContato.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sivic_contatos).should eq([sivic_contato])
    end
  end

  describe "GET show" do
    it "assigns the requested sivic_contato as @sivic_contato" do
      sivic_contato = SivicContato.create! valid_attributes
      get :show, {:id => sivic_contato.to_param}, valid_session
      assigns(:sivic_contato).should eq(sivic_contato)
    end
  end

  describe "GET new" do
    it "assigns a new sivic_contato as @sivic_contato" do
      get :new, {}, valid_session
      assigns(:sivic_contato).should be_a_new(SivicContato)
    end
  end

  describe "GET edit" do
    it "assigns the requested sivic_contato as @sivic_contato" do
      sivic_contato = SivicContato.create! valid_attributes
      get :edit, {:id => sivic_contato.to_param}, valid_session
      assigns(:sivic_contato).should eq(sivic_contato)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SivicContato" do
        expect {
          post :create, {:sivic_contato => valid_attributes}, valid_session
        }.to change(SivicContato, :count).by(1)
      end

      it "assigns a newly created sivic_contato as @sivic_contato" do
        post :create, {:sivic_contato => valid_attributes}, valid_session
        assigns(:sivic_contato).should be_a(SivicContato)
        assigns(:sivic_contato).should be_persisted
      end

      it "redirects to the created sivic_contato" do
        post :create, {:sivic_contato => valid_attributes}, valid_session
        response.should redirect_to(SivicContato.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sivic_contato as @sivic_contato" do
        # Trigger the behavior that occurs when invalid params are submitted
        SivicContato.any_instance.stub(:save).and_return(false)
        post :create, {:sivic_contato => { "desc_nome" => "invalid value" }}, valid_session
        assigns(:sivic_contato).should be_a_new(SivicContato)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SivicContato.any_instance.stub(:save).and_return(false)
        post :create, {:sivic_contato => { "desc_nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sivic_contato" do
        sivic_contato = SivicContato.create! valid_attributes
        # Assuming there are no other sivic_contatos in the database, this
        # specifies that the SivicContato created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SivicContato.any_instance.should_receive(:update).with({ "desc_nome" => "MyString" })
        put :update, {:id => sivic_contato.to_param, :sivic_contato => { "desc_nome" => "MyString" }}, valid_session
      end

      it "assigns the requested sivic_contato as @sivic_contato" do
        sivic_contato = SivicContato.create! valid_attributes
        put :update, {:id => sivic_contato.to_param, :sivic_contato => valid_attributes}, valid_session
        assigns(:sivic_contato).should eq(sivic_contato)
      end

      it "redirects to the sivic_contato" do
        sivic_contato = SivicContato.create! valid_attributes
        put :update, {:id => sivic_contato.to_param, :sivic_contato => valid_attributes}, valid_session
        response.should redirect_to(sivic_contato)
      end
    end

    describe "with invalid params" do
      it "assigns the sivic_contato as @sivic_contato" do
        sivic_contato = SivicContato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SivicContato.any_instance.stub(:save).and_return(false)
        put :update, {:id => sivic_contato.to_param, :sivic_contato => { "desc_nome" => "invalid value" }}, valid_session
        assigns(:sivic_contato).should eq(sivic_contato)
      end

      it "re-renders the 'edit' template" do
        sivic_contato = SivicContato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SivicContato.any_instance.stub(:save).and_return(false)
        put :update, {:id => sivic_contato.to_param, :sivic_contato => { "desc_nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sivic_contato" do
      sivic_contato = SivicContato.create! valid_attributes
      expect {
        delete :destroy, {:id => sivic_contato.to_param}, valid_session
      }.to change(SivicContato, :count).by(-1)
    end

    it "redirects to the sivic_contatos list" do
      sivic_contato = SivicContato.create! valid_attributes
      delete :destroy, {:id => sivic_contato.to_param}, valid_session
      response.should redirect_to(sivic_contatos_url)
    end
  end

end
