require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SivicAtividadesController do

  # This should return the minimal set of attributes required to create a valid
  # SivicAtividade. As you add validations to SivicAtividade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome_atividade" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SivicAtividadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sivic_atividades as @sivic_atividades" do
      sivic_atividade = SivicAtividade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sivic_atividades).should eq([sivic_atividade])
    end
  end

  describe "GET show" do
    it "assigns the requested sivic_atividade as @sivic_atividade" do
      sivic_atividade = SivicAtividade.create! valid_attributes
      get :show, {:id => sivic_atividade.to_param}, valid_session
      assigns(:sivic_atividade).should eq(sivic_atividade)
    end
  end

  describe "GET new" do
    it "assigns a new sivic_atividade as @sivic_atividade" do
      get :new, {}, valid_session
      assigns(:sivic_atividade).should be_a_new(SivicAtividade)
    end
  end

  describe "GET edit" do
    it "assigns the requested sivic_atividade as @sivic_atividade" do
      sivic_atividade = SivicAtividade.create! valid_attributes
      get :edit, {:id => sivic_atividade.to_param}, valid_session
      assigns(:sivic_atividade).should eq(sivic_atividade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SivicAtividade" do
        expect {
          post :create, {:sivic_atividade => valid_attributes}, valid_session
        }.to change(SivicAtividade, :count).by(1)
      end

      it "assigns a newly created sivic_atividade as @sivic_atividade" do
        post :create, {:sivic_atividade => valid_attributes}, valid_session
        assigns(:sivic_atividade).should be_a(SivicAtividade)
        assigns(:sivic_atividade).should be_persisted
      end

      it "redirects to the created sivic_atividade" do
        post :create, {:sivic_atividade => valid_attributes}, valid_session
        response.should redirect_to(SivicAtividade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sivic_atividade as @sivic_atividade" do
        # Trigger the behavior that occurs when invalid params are submitted
        SivicAtividade.any_instance.stub(:save).and_return(false)
        post :create, {:sivic_atividade => { "nome_atividade" => "invalid value" }}, valid_session
        assigns(:sivic_atividade).should be_a_new(SivicAtividade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SivicAtividade.any_instance.stub(:save).and_return(false)
        post :create, {:sivic_atividade => { "nome_atividade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sivic_atividade" do
        sivic_atividade = SivicAtividade.create! valid_attributes
        # Assuming there are no other sivic_atividades in the database, this
        # specifies that the SivicAtividade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SivicAtividade.any_instance.should_receive(:update).with({ "nome_atividade" => "MyString" })
        put :update, {:id => sivic_atividade.to_param, :sivic_atividade => { "nome_atividade" => "MyString" }}, valid_session
      end

      it "assigns the requested sivic_atividade as @sivic_atividade" do
        sivic_atividade = SivicAtividade.create! valid_attributes
        put :update, {:id => sivic_atividade.to_param, :sivic_atividade => valid_attributes}, valid_session
        assigns(:sivic_atividade).should eq(sivic_atividade)
      end

      it "redirects to the sivic_atividade" do
        sivic_atividade = SivicAtividade.create! valid_attributes
        put :update, {:id => sivic_atividade.to_param, :sivic_atividade => valid_attributes}, valid_session
        response.should redirect_to(sivic_atividade)
      end
    end

    describe "with invalid params" do
      it "assigns the sivic_atividade as @sivic_atividade" do
        sivic_atividade = SivicAtividade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SivicAtividade.any_instance.stub(:save).and_return(false)
        put :update, {:id => sivic_atividade.to_param, :sivic_atividade => { "nome_atividade" => "invalid value" }}, valid_session
        assigns(:sivic_atividade).should eq(sivic_atividade)
      end

      it "re-renders the 'edit' template" do
        sivic_atividade = SivicAtividade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SivicAtividade.any_instance.stub(:save).and_return(false)
        put :update, {:id => sivic_atividade.to_param, :sivic_atividade => { "nome_atividade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sivic_atividade" do
      sivic_atividade = SivicAtividade.create! valid_attributes
      expect {
        delete :destroy, {:id => sivic_atividade.to_param}, valid_session
      }.to change(SivicAtividade, :count).by(-1)
    end

    it "redirects to the sivic_atividades list" do
      sivic_atividade = SivicAtividade.create! valid_attributes
      delete :destroy, {:id => sivic_atividade.to_param}, valid_session
      response.should redirect_to(sivic_atividades_url)
    end
  end

end
