require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SivicPeriodicidadeconsController do

  # This should return the minimal set of attributes required to create a valid
  # SivicPeriodicidadecon. As you add validations to SivicPeriodicidadecon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "desc_periodicidade" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SivicPeriodicidadeconsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sivic_periodicidadecons as @sivic_periodicidadecons" do
      sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sivic_periodicidadecons).should eq([sivic_periodicidadecon])
    end
  end

  describe "GET show" do
    it "assigns the requested sivic_periodicidadecon as @sivic_periodicidadecon" do
      sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
      get :show, {:id => sivic_periodicidadecon.to_param}, valid_session
      assigns(:sivic_periodicidadecon).should eq(sivic_periodicidadecon)
    end
  end

  describe "GET new" do
    it "assigns a new sivic_periodicidadecon as @sivic_periodicidadecon" do
      get :new, {}, valid_session
      assigns(:sivic_periodicidadecon).should be_a_new(SivicPeriodicidadecon)
    end
  end

  describe "GET edit" do
    it "assigns the requested sivic_periodicidadecon as @sivic_periodicidadecon" do
      sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
      get :edit, {:id => sivic_periodicidadecon.to_param}, valid_session
      assigns(:sivic_periodicidadecon).should eq(sivic_periodicidadecon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SivicPeriodicidadecon" do
        expect {
          post :create, {:sivic_periodicidadecon => valid_attributes}, valid_session
        }.to change(SivicPeriodicidadecon, :count).by(1)
      end

      it "assigns a newly created sivic_periodicidadecon as @sivic_periodicidadecon" do
        post :create, {:sivic_periodicidadecon => valid_attributes}, valid_session
        assigns(:sivic_periodicidadecon).should be_a(SivicPeriodicidadecon)
        assigns(:sivic_periodicidadecon).should be_persisted
      end

      it "redirects to the created sivic_periodicidadecon" do
        post :create, {:sivic_periodicidadecon => valid_attributes}, valid_session
        response.should redirect_to(SivicPeriodicidadecon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sivic_periodicidadecon as @sivic_periodicidadecon" do
        # Trigger the behavior that occurs when invalid params are submitted
        SivicPeriodicidadecon.any_instance.stub(:save).and_return(false)
        post :create, {:sivic_periodicidadecon => { "desc_periodicidade" => "invalid value" }}, valid_session
        assigns(:sivic_periodicidadecon).should be_a_new(SivicPeriodicidadecon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SivicPeriodicidadecon.any_instance.stub(:save).and_return(false)
        post :create, {:sivic_periodicidadecon => { "desc_periodicidade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sivic_periodicidadecon" do
        sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
        # Assuming there are no other sivic_periodicidadecons in the database, this
        # specifies that the SivicPeriodicidadecon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SivicPeriodicidadecon.any_instance.should_receive(:update).with({ "desc_periodicidade" => "MyString" })
        put :update, {:id => sivic_periodicidadecon.to_param, :sivic_periodicidadecon => { "desc_periodicidade" => "MyString" }}, valid_session
      end

      it "assigns the requested sivic_periodicidadecon as @sivic_periodicidadecon" do
        sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
        put :update, {:id => sivic_periodicidadecon.to_param, :sivic_periodicidadecon => valid_attributes}, valid_session
        assigns(:sivic_periodicidadecon).should eq(sivic_periodicidadecon)
      end

      it "redirects to the sivic_periodicidadecon" do
        sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
        put :update, {:id => sivic_periodicidadecon.to_param, :sivic_periodicidadecon => valid_attributes}, valid_session
        response.should redirect_to(sivic_periodicidadecon)
      end
    end

    describe "with invalid params" do
      it "assigns the sivic_periodicidadecon as @sivic_periodicidadecon" do
        sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SivicPeriodicidadecon.any_instance.stub(:save).and_return(false)
        put :update, {:id => sivic_periodicidadecon.to_param, :sivic_periodicidadecon => { "desc_periodicidade" => "invalid value" }}, valid_session
        assigns(:sivic_periodicidadecon).should eq(sivic_periodicidadecon)
      end

      it "re-renders the 'edit' template" do
        sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SivicPeriodicidadecon.any_instance.stub(:save).and_return(false)
        put :update, {:id => sivic_periodicidadecon.to_param, :sivic_periodicidadecon => { "desc_periodicidade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sivic_periodicidadecon" do
      sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
      expect {
        delete :destroy, {:id => sivic_periodicidadecon.to_param}, valid_session
      }.to change(SivicPeriodicidadecon, :count).by(-1)
    end

    it "redirects to the sivic_periodicidadecons list" do
      sivic_periodicidadecon = SivicPeriodicidadecon.create! valid_attributes
      delete :destroy, {:id => sivic_periodicidadecon.to_param}, valid_session
      response.should redirect_to(sivic_periodicidadecons_url)
    end
  end

end
